apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: hw13
spec:
  restartPolicy: Never
  containers:
    - name: load
      image: busybox:1.36
      resources:
        requests: {cpu: 20m, memory: 8Mi}
        limits: {cpu: 200m, memory: 32Mi}
      command: [/bin/sh, -c]
      args:
        - |
          for worker in 1 2 3 4 5 6 7 8; do
            (while true; do wget -q -O /dev/null http://web-service; done) &
          done
          wait
