apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../app]
images:
  - name: ghcr.io/rajasurya-rjs/devops-heros/ops-notes
    newTag: e1b3f65fc09b6226b28141fc6748c03ceda87c93
