apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_NAME: {{ .Values.app.name | quote }}
  ENVIRONMENT: {{ .Values.app.environment | quote }}
  index.html: |
    <!doctype html><h1>{{ .Values.app.name }}</h1>
    <p>Environment: {{ .Values.app.environment }} | Version: {{ .Values.app.version }}</p>
